esphome:
  name: ${device_name}
  project:
    name: "Mark.Sonoff_T1EU2C-TX_Series"
    version: "2.8"       # ← ZOBRAZÍ sa v Home Assistante

ota:
    platform: http_request
    url: https://raw.githubusercontent.com/Daddy1976/Sonoff_tx_switch_esphome/main/tx_switch.yaml
    password: !secret ota_password

  on_boot:
    priority: -100
    then:
      - script.execute: update_led_state

esp8266:
  board: esp01_1m
  framework:
    version: recommended
    
globals:
  - id: relay1_total_runtime
    type: uint32_t
    restore_value: yes
    initial_value: "0"

  - id: relay1_start_time
    type: uint32_t
    restore_value: no

wifi:
  networks:
    - ssid: ${wifi_ssid}
      password: ${wifi_pass}
  fast_connect: true
  min_auth_mode: WPA2

  on_connect:
    - script.execute: update_led_state
  on_disconnect:
    - script.execute: update_led_state

logger:
  level: INFO

safe_mode:
  disabled: true

api:
  reboot_timeout: 15min
  on_client_connected:
    - script.execute: update_led_state
  on_client_disconnected:
    - script.execute: update_led_state

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
  js_url: "https://oi.esphome.io/v3/www.js"
  version: 3
  include_internal: true


###########################################
# S E N Z O R Y
###########################################

sensor:
  - platform: uptime
    name: Uptime

  - platform: wifi_signal
    id: wifi_signal_db
    name: RSSI
    update_interval: 30s
    entity_category: "diagnostic"
    icon: mdi:wifi

  # PREVÁDZKOVÝ ČAS RELÉ 1
  - platform: template
    name: "Celkový Čas"
    id: relay_1_state_numeric
    unit_of_measurement: "s"
    device_class: duration
    accuracy_decimals: 0
    icon: mdi:timer-outline
    

###############################
# Reset relay on time counter #
###############################
    

time:
  - platform: homeassistant
    id: ha_time
    on_time:
      - seconds: 0
        minutes: 0
        hours: 0
        days_of_month: 1
        then:
          - lambda: |-
              id(relay1_total_runtime) = 0;
              id(relay_1_state_numeric).publish_state(0);




###########################################
# T E X T  S E N Z O R Y
###########################################

text_sensor:
  - platform: version
    name: ESP Version
    entity_category: "diagnostic"
  - platform: wifi_info
    ip_address:
      name: IP
      entity_category: "diagnostic"
      icon: mdi:ip-network
    ssid:
      name: SSID
      entity_category: "diagnostic"
      icon: mdi:access-point
    bssid:
      name: "Connected"
      filters:
        substitute:
          - "48:8F:5A:17:5B:DD -> AP strecha 2ghz"
          - "48:8F:5A:17:5C:01 -> AP obyvacka 2ghz"

      entity_category: "diagnostic"
      icon: mdi:router-wireless


###########################################
# B I N Á R N E  S E N Z O R Y
###########################################

binary_sensor:
  - platform: status
    name: Status
    on_state:
      - script.execute: update_led_state

  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sonoff TX Touchpad 1"
    on_press:
      - script.execute: led_flash
      - switch.toggle: relay_1


###########################################
# R E L É
###########################################

switch:
  - platform: gpio
    name: ${device_name} switch 1
    pin: GPIO012
    id: relay_1
    icon: mdi:electric-switch
    on_turn_on:
      - lambda: |-
            id(relay1_start_time) = millis() / 1000;
    on_turn_off:
      - lambda: |-
            uint32_t now = millis() / 1000;
            id(relay1_total_runtime) += (now - id(relay1_start_time));
            id(relay_1_state_numeric).publish_state(id(relay1_total_runtime));


###########################################
# L E D  &  W M
###########################################

output:
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: true
    frequency: 1000 Hz

light:
  - platform: monochromatic
    id: blue_led_light
    name: Blue LED
    output: blue_led
    internal: true


###########################################
# S K R I P T Y
###########################################

script:

  # 1) Krátke prebliknutie
  - id: led_flash
    then:
      - output.set_level:
          id: blue_led
          level: 100%
      - delay: 150ms
      - script.execute: update_led_state


  # 2) Riadi hlavnú LED logiku
  - id: update_led_state
    mode: restart
    then:
      - script.stop: led_breath
      - script.stop: led_fast_blink

      - if:
          condition: wifi.connected
          then:
            - if:
                condition: api.connected
                then:
                  - output.set_level:
                      id: blue_led
                      level: 10%
                else:
                  - script.execute: led_breath
          else:
            - script.execute: led_fast_blink


  # 3) Breathing režim pri WiFi OK a API offline
  - id: led_breath
    mode: restart
    then:
      - while:
          condition: wifi.connected
          then:
            - output.set_level:
                id: blue_led
                level: 90%
            - delay: 500ms
            - output.set_level:
                id: blue_led
                level: 30%
            - delay: 500ms


  # 4) Rýchle blikanie pri strate WiFi
  - id: led_fast_blink
    mode: restart
    then:
      - while:
          condition:
            not: wifi.connected
          then:
            - output.set_level:
                id: blue_led
                level: 100%
            - delay: 100ms
            - output.set_level:
                id: blue_led
                level: 0%
            - delay: 100ms
