substitutions:
//
//  Sonoff-TX-switch.yaml
//  
//
//  Created by Marek Halma on 12/08/2023.
//

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

  on_boot:
    priority: -10
    then:
      - light.turn_on: blue_led_light

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

logger:
  
api:
  reboot_timeout: 15min

ota:

# the web_server & sensor components can be removed without affecting core functionaility.

web_server:
  port: 80

mqtt:
  topic_prefix: /homeassistant/tx/$upper_devicename
  discovery: false
  broker: ${broker_ip}
  port: 1883
  username: ${broker_user}
  password: ${broker_password}
  discovery_prefix: homeassistant

sensor:
  # Uptime sensor
  - platform: uptime
    name: $device_name uptime
  # WiFi Signal sensor
  - platform: wifi_signal
    id: wifi_signal_db
    name: RSSI
    entity_category: "diagnostic"
    update_interval: 30s
  # Reports the WiFi signal strength in %
  - platform: copy
    source_id: wifi_signal_db
    name: $device_name WiFi Signal
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
#######################################
# Device specific Config Begins Below #
#######################################

text_sensor:
  - platform: version
    name: Date
  - platform: wifi_info
    ip_address:
      name: $device_name ip
    ssid:
      name: $device_name ssid
    bssid:
      name: $device_name bssid

binary_sensor:
  # the 7 lines below define the reset button
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true  # hides reset switch from HomeAssistant
    filters:
      - invert:
      - delayed_off: 10ms
  # the 3 lines below toggle the main relay on press of reset button
    on_press:
      - switch.toggle: relay_1
      - mqtt.publish_json:
          topic: svetlo
          payload: |-
              root["key"] = id(relay_1).state;
  - platform: status
    name: ${device_name} Status

  # the 13 lines below toggle the main relay on command
switch:
  - platform: gpio
    name: ${device_name} switch
    # internal: true  # hides relay toggle from HomeAssistant
    pin: GPIO012
    id: relay_1

output:
  # the 3 lines below control the main relay
  - platform: gpio
    pin: GPIO4
    id: main_light_relay
  # the 3 lines below control the Blue LED
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  # the 4 lines below define the main relay as a light
  - platform: binary
    name: ${device_name}_light # you can enter a custom name to appear in HomeAsistant here.
    output: main_light_relay
    id: light_id
    internal: True
  # the 4 lines below define the Blue LED light on Sonoff Mini, to expose in HomeAssistant remove line "internal: true"
  - platform: monochromatic
    name: ${device_name}_blueled
    output: blue_led
    id: blue_led_light
    internal: True
