#
#   Sonoff-TX-switch.yaml 3 Relay support
#
#
#   Created by Marek Halma on 12/08/2023.
#
#   Add new file .yaml and copy this stricture

#   substitutions:
#
#       device_name: "test"
#       wifi_ssid: !secret wifi_ssid
#       wifi_pass: !secret wifi_password
#       broker_ip: "#BROKER_IP#" my broker is CERBO GX Victron or Homeassistant with Mosquitto
#       broker_user: !secret user
#       broker_password: !secret password
#
#   packages:
#       remote_package:
#           url: https://github.com/Daddy1976/Sonoff_tx_switch_esphome
#           ref: main
#           files: [tx_switch.yaml]
#           refresh: 300s
        


esphome:
  name: ${device_name}

  on_boot:
    priority: -100
    then:
      - script.execute: update_led_state

project:
  name: "Mark.Sonoff T1EU2C-TX Series"
  version: "2.0"

esp8266:
  board: esp01_1m
  framework:
    version: recommended

wifi:
  networks:
    - ssid: ${wifi_ssid}
      password: ${wifi_pass}
  fast_connect: True
  on_connect:
    - script.execute: update_led_state
  on_disconnect:
    - script.execute: update_led_state

logger:

api:
  reboot_timeout: 15min
  on_client_connected:
    - script.execute: update_led_state
  on_client_disconnected:
    - script.execute: update_led_state

ota:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
  js_url: "https://oi.esphome.io/v3/www.js"
  version: 3
  include_internal: True

sensor:
  - platform: uptime
    name: Uptime

  - platform: wifi_signal
    id: wifi_signal_db
    name: RSSI
    update_interval: 30s

text_sensor:
  - platform: version
    name: Date
  - platform: wifi_info
    ip_address:
      name: IP
    ssid:
      name: SSID
    bssid:
      name: Connected AP

binary_sensor:
  - name: Status
    platform: status
    on_state:
      - script.execute: update_led_state

  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sonoff TX Touchpad 1"
    on_press:
      - script.execute: led_flash
      - switch.toggle: relay_1

switch:
  - platform: gpio
    name: ${device_name} switch 1
    pin: GPIO012
    id: relay_1

output:
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True
    frequency: 1000 Hz

light:
  - platform: monochromatic
    id: blue_led_light
    name: Blue LED
    output: blue_led
    internal: True

script:

  # ⚡ krátke prebliknutie pri stlačení tlačidla
  - id: led_flash
    then:
      - output.set_level:
          id: blue_led
          level: 100%
      - delay: 150ms
      - script.execute: update_led_state

  # 🟦 hlavná logika LED stavového systému
  - id: update_led_state
    mode: restart
    then:
      - if:
          condition:
            wifi.connected:
          then:
            - if:
                condition:
                  api.connected:
                then:
                  # WIFI OK + API OK → jemné svetlo
                  - output.set_level:
                      id: blue_led
                      level: 20%
                else:
                  # WIFI OK + API OFF → breathing efekt
                  - script.execute: led_breath
          else:
            # WIFI OFF → rýchle blikanie
            - script.execute: led_fast_blink

  # ✨ breathing efekt pri HomeAssistant OFF
  - id: led_breath
    mode: restart
    then:
      - while:
          condition:
            wifi.connected
          then:
            - output.set_level:
                id: blue_led
                level: 10%
            - delay: 500ms
            - output.set_level:
                id: blue_led
                level: 30%
            - delay: 500ms

  # 🚨 rýchle blikanie pri strate WiFi
  - id: led_fast_blink
    mode: restart
    then:
      - while:
          condition:
            not:
              wifi.connected:
          then:
            - output.set_level:
                id: blue_led
                level: 100%
            - delay: 200ms
            - output.set_level:
                id: blue_led
                level: 0%
            - delay: 200ms
