#
#   Sonoff-TX-switch.yaml 3 Relay support
#
#
#   Created by Marek Halma on 12/08/2023.
#
#   Add new file .yaml and copy this stricture

#   substitutions:
#
#       device_name: "test"
#       wifi_ssid: !secret wifi_ssid
#       wifi_pass: !secret wifi_password
#       broker_ip: "#BROKER_IP#" my broker is CERBO GX Victron or Homeassistant with Mosquitto
#       broker_user: !secret user
#       broker_password: !secret password
#
#   packages:
#       remote_package:
#           url: https://github.com/Daddy1976/Sonoff_tx_switch_esphome
#           ref: main
#           files: [tx_switch.yaml]
#           refresh: 300s
        


esphome:
  name: ${device_name}
  project:
    name: "Mark.Sonoff T1EU2C-TX Series"
    version: "2.2"

  on_boot:
    priority: -100
    then:
      - script.execute: update_led_state

esp8266:
  board: esp01_1m
  framework:
    version: recommended

wifi:
  networks:
    - ssid: ${wifi_ssid}
      password: ${wifi_pass}
  fast_connect: True

  on_connect:
    - script.execute: update_led_state
  on_disconnect:
    - script.execute: update_led_state

logger:
    level: INFO

api:
  reboot_timeout: 15min
  on_client_connected:
    - script.execute: update_led_state
  on_client_disconnected:
    - script.execute: update_led_state

ota:
  platform: esphome
  password: !secret ota_password

  on_begin:
    then:
      - logger.log: "OTA start"

  on_progress:
    then:
      - logger.log:
          format: "OTA progress %0.1f%%"
          args: ["x"]

  on_end:
    then:
      - logger.log: "OTA end"

  on_error:
    then:
      - logger.log:
          format: "OTA update error %d"
          args: ["x"]

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
  js_url: "https://oi.esphome.io/v3/www.js"
  version: 3
  include_internal: True


###########################
# S E N Z O R Y
###########################

sensor:
  - platform: uptime
    name: Uptime
  
  - platform: wifi_signal
    id: wifi_signal_db
    name: RSSI
    entity_category: "diagnostic"
    update_interval: 30s
    icon: mdi:wifi

  # -------------------------------
  # PREVÁDZKOVÝ ČAS RELÉ 1 (hodiny / minúty)
  # -------------------------------

  - platform: template
    id: relay_1_state_numeric
    internal: true
    update_interval: 1s
    lambda: |-
      return id(relay_1).state ? 1.0 : 0.0;

  - platform: integration
    name: "Relay 1 Runtime Total"
    sensor: relay_1_state_numeric
    time_unit: h
    id: relay_1_runtime_total

  - platform: integration
    name: "Relay 1 Runtime Today"
    sensor: relay_1_state_numeric
    time_unit: min
    id: relay_1_runtime_today
    restore: false


###########################
# Č A S
###########################

time:
  - platform: sntp
    id: sntp_time
    on_time:
      # reset denneho runtime o polnoci
      - seconds: 0
        minutes: 0
        hours: 0
        then:
          - lambda: |-
              id(relay_1_runtime_today).reset();


###########################
# T E X T O V É  S E N Z O R Y
###########################

text_sensor:
  - platform: version
    name: Date
    entity_category: "diagnostic"
  - platform: wifi_info
    ip_address:
      name: IP
      entity_category: "diagnostic"
      icon: mdi:ip-network
    ssid:
      name: SSID
      entity_category: "diagnostic"
      icon: mdi:access-point
    bssid:
      name: "Connected"
      filters:
        substitute:
          - "48:8F:5A:17:5B:DD -> AP strecha 2ghz"
          - "48:8F:5A:17:5C:01 -> AP obyvacka 2ghz"

      entity_category: "diagnostic"
      icon: mdi:router-wireless


###########################
# B I N Á R N E  S E N Z O R Y
###########################

binary_sensor:
  - name: Status
    platform: status
    on_state:
      - script.execute: update_led_state

  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sonoff TX Touchpad 1"
    on_press:
      - script.execute: led_flash
      - switch.toggle: relay_1


###########################
# R E L É
###########################

switch:
  - platform: gpio
    name: ${device_name} switch 1
    pin: GPIO012
    id: relay_1
    icon: mdi:electric-switch


###########################
# L E D  W M  &  L I G H T
###########################

output:
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True
    frequency: 1000 Hz

light:
  - platform: monochromatic
    id: blue_led_light
    name: Blue LED
    output: blue_led
    internal: True


###########################
# S K R I P T Y
###########################

script:

  # Krátke prebliknutie
  - id: led_flash
    then:
      - output.set_level:
          id: blue_led
          level: 100%
      - delay: 150ms
      - script.execute: update_led_state

  # Riadenie hlavného LED stavu
  - id: update_led_state
    mode: restart
    then:
      - if:
          condition: wifi.connected
          then:
            # WIFI OK
            - if:
                condition: api.connected
                then:
                  # API OK → jemné svetlo
                  - script.stop: led_breath
                  - script.stop: led_fast_blink
                  - output.set_level:
                      id: blue_led
                      level: 20%
                else:
                  # API OFF → breathing
                  - script.execute: led_breath
          else:
            # WIFI OFF → rýchle blikanie
            - script.execute: led_fast_blink

  # Breathing LED – zastaví sa keď API príde online
  - id: led_breath
    mode: restart
    then:
      - while:
          condition:
            and:
              - wifi.connected
              - not: api.connected
          then:
            - output.set_level:
                id: blue_led
                level: 10%
            - delay: 500ms

            - if:
                condition: api.connected
                then:
                  - script.stop: led_breath
                  - script.execute: update_led_state

            - output.set_level:
                id: blue_led
                level: 30%
            - delay: 500ms

  # Rýchle blikanie pri strate WiFi
  - id: led_fast_blink
    mode: restart
    then:
      - while:
          condition:
            not: wifi.connected
          then:
            - output.set_level:
                id: blue_led
                level: 100%
            - delay: 200ms
            - output.set_level:
                id: blue_led
                level: 0%
            - delay: 200ms
