esphome:
  name: terasa
  friendly_name: Terasa

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

api:

ota:
  password: !secret ota_password

logger:

web_server:
  port: 80

time:
  - platform: sntp
    id: sntp_time
    on_time:
      - seconds: 0
        minutes: 0
        hours: 0
        then:
          - lambda: |-
              id(relay_1_runtime_today).reset();

sensor:
  - platform: uptime
    name: "Uptime"

  - platform: wifi_signal
    name: "RSSI"
    update_interval: 30s

  - platform: template
    id: relay_1_state_numeric
    internal: true
    update_interval: 1s
    lambda: |-
      return id(relay_1).state ? 1 : 0;

  - platform: integration
    name: "Relay 1 Runtime Total"
    sensor: relay_1_state_numeric
    time_unit: h
    id: relay_1_runtime_total
    restore: true

  - platform: integration
    name: "Relay 1 Runtime Today"
    sensor: relay_1_state_numeric
    time_unit: min
    id: relay_1_runtime_today
    restore: true

text_sensor:
  - platform: version
    name: "ESPHome Version"

binary_sensor:
  - platform: status
    name: "Status"

  - platform: gpio
    name: "Touchpad 1"
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    on_press:
      - switch.toggle: relay_1

switch:
  - platform: gpio
    name: "Terasa Relay 1"
    pin: GPIO12
    id: relay_1

output:
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: true

light:
  - platform: monochromatic
    name: "Blue LED"
    id: blue_led_light
    output: blue_led
    internal: true
